AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Eventual bank account operation
  
Globals:
  Function:
    Timeout: 10

Resources:
  AccountOperationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dynamo-handler/
      Handler: app.handler
      Runtime: nodejs18.x
      Policies:
        - DynamoDBCrudPolicy:
            TableName: account
        - SQSPollerPolicy:
            QueueName: !GetAtt MySqsQueue.QueueName
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt MySqsQueue.Arn
            BatchSize: 100
            MaximumBatchingWindowInSeconds: 2
  MySqsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: account_transfer

Outputs:
  Function:
    Description: "Transfer simulator function ARN"
    Value: !GetAtt AccountOperationFunction.Arn
